server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: users_scheme
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: testtest
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    properties.hibernate.default_schema: users_scheme
    hibernate:
      ddl-auto: validate
    show-sql: true


